# Generated by Django 5.0.6 on 2024-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
